# Generated by Django 4.0.3 on 2023-03-16 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('regions', '0002_remove_region_id_alter_region_k_region'),
        ('warehouse', '0002_alter_bode_prod_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='metodopago',
            fields=[
                ('k_metodo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('t_descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('k_pedido', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('f_creacion', models.DateField()),
                ('i_estado', models.CharField(max_length=1)),
                ('n_direccion', models.CharField(max_length=50)),
                ('k_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cliente')),
                ('k_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.region')),
            ],
        ),
        migrations.CreateModel(
            name='pagopedido',
            fields=[
                ('k_pagopedido', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('n_valor', models.DecimalField(decimal_places=0, max_digits=10)),
                ('i_estado', models.CharField(max_length=1)),
                ('f_pago', models.DateField()),
                ('k_metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.metodopago')),
                ('k_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='caliservicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_calificacion', models.DecimalField(decimal_places=0, max_digits=1)),
                ('k_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='pedi_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_cantidad', models.DecimalField(decimal_places=0, max_digits=5)),
                ('n_preciou', models.DecimalField(decimal_places=0, max_digits=6)),
                ('k_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.pedido')),
                ('k_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.producto')),
            ],
            options={
                'unique_together': {('k_pedido', 'k_producto')},
            },
        ),
    ]
