# Generated by Django 4.0.3 on 2023-03-16 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pedi_item',
            unique_together=set(),
        ),
    ]
