version: '3.1'

services:
  backend:
    image: bd2-back
    volumes:
      - .:/app
    networks:
      - proxy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints: [node.hostname==juferoga.live]    
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.port=8000"
        - "traefik.http.routers.api-secure.entrypoints=websecure"
        - "traefik.http.routers.api-secure.rule=Host(`bd-back.juferoga.live`)"
networks:
      proxy:
        external: true