version: '3.1'

services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    networks:
      - proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.port=8000"
      #cambiar por nombre del api
      #adicionar desde aquí para el funcionamiento de una container con traefik
      - "traefik.http.routers.api-secure.entrypoints=websecure"
      - "traefik.http.routers.api-secure.rule=host(´api.redflox.com´)"
networks:
      proxy:
        external: true