# Generated by Django 4.1.7 on 2023-03-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options_alter_user_managers_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='k_usuario',
            field=models.IntegerField(null=True),
        ),
    ]
