# Generated by Django 4.1.7 on 2023-03-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_k_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='k_usuario',
            field=models.BigIntegerField(null=True),
        ),
    ]
