version: '3'

services:
  db:
    image: oracle/database:18.4.0-xe
    environment:
      - ORACLE_PWD=Admin123..
    ports: 
      - "11521:11521"

  web:
    build: .
    volumes:
      - ../bdproject/:/code
      - ./requirements.txt:/code/requirements.txt
    command: bash -c "python -m pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db

