REM INSERTING into  ASIGNATURA
Insert into ASIGNATURA (K_ASIGNATURA,K_PLAN,N_NOMBRE,Q_NROCREDITOS,Q_NIVEL) values (20141,'2006CR','Bases de Datos I',3,9);
Insert into ASIGNATURA (K_ASIGNATURA,K_PLAN,N_NOMBRE,Q_NROCREDITOS,Q_NIVEL) values (20041,'2002AS','Bases de Datos I',null,9);
Insert into ASIGNATURA (K_ASIGNATURA,K_PLAN,N_NOMBRE,Q_NROCREDITOS,Q_NIVEL) values (20142,'2006CR','Bases de Datos II',3,10);
