REM INSERTING into  ESTUDIANTE_NOTA
Insert into ESTUDIANTE_NOTA (K_CODEST,K_CODGRUPO,K_NOTA,V_NOTA) values (100,1,'N1',1);
Insert into ESTUDIANTE_NOTA (K_CODEST,K_CODGRUPO,K_NOTA,V_NOTA) values (100,1,'N2',1);
Insert into ESTUDIANTE_NOTA (K_CODEST,K_CODGRUPO,K_NOTA,V_NOTA) values (100,1,'EF',1);
Insert into ESTUDIANTE_NOTA (K_CODEST,K_CODGRUPO,K_NOTA,V_NOTA) values (100,3,'N1',3.5);
Insert into ESTUDIANTE_NOTA (K_CODEST,K_CODGRUPO,K_NOTA,V_NOTA) values (100,3,'EF',3.5);
Insert into ESTUDIANTE_NOTA (K_CODEST,K_CODGRUPO,K_NOTA,V_NOTA) values (100,4,'N1',5);
Insert into ESTUDIANTE_NOTA (K_CODEST,K_CODGRUPO,K_NOTA,V_NOTA) values (101,4,'N1',3.5);
