REM INSERTING into ESTUDIANTE_GRUPO
Insert into ESTUDIANTE_GRUPO (K_CODEST,K_CODGRUPO,V_NOTADEF) values (100,1,1);
Insert into ESTUDIANTE_GRUPO (K_CODEST,K_CODGRUPO,V_NOTADEF) values (100,3,3.5);
Insert into ESTUDIANTE_GRUPO (K_CODEST,K_CODGRUPO,V_NOTADEF) values (100,4,null);
Insert into ESTUDIANTE_GRUPO (K_CODEST,K_CODGRUPO,V_NOTADEF) values (101,4,null); 
