REM INSERTING into  GRHRSA
Insert into GRHRSA (K_CODGRUPO,K_HORARIO,K_SALON,K_SEDE) values (1,1,'501','SABCA');
Insert into GRHRSA (K_CODGRUPO,K_HORARIO,K_SALON,K_SEDE) values (1,2,'501','SABCA');
Insert into GRHRSA (K_CODGRUPO,K_HORARIO,K_SALON,K_SEDE) values (3,1,'504','SABCA');
Insert into GRHRSA (K_CODGRUPO,K_HORARIO,K_SALON,K_SEDE) values (3,2,'504','SABCA');
Insert into GRHRSA (K_CODGRUPO,K_HORARIO,K_SALON,K_SEDE) values (4,3,'501','SABCA');
Insert into GRHRSA (K_CODGRUPO,K_HORARIO,K_SALON,K_SEDE) values (4,4,'501','SABCA');
