REM INSERTING into  HORARIO
Insert into HORARIO (K_HORARIO,Q_HORAINI,Q_HORAFIN,N_DIA) values (1,'10:00','12:00','LU');
Insert into HORARIO (K_HORARIO,Q_HORAINI,Q_HORAFIN,N_DIA) values (2,'10:00','12:00','MI');
Insert into HORARIO (K_HORARIO,Q_HORAINI,Q_HORAFIN,N_DIA) values (3,'14:00','16:00','MA');
Insert into HORARIO (K_HORARIO,Q_HORAINI,Q_HORAFIN,N_DIA) values (4,'14:00','16:00','JU');
