# Generated by Django 4.0.3 on 2023-03-16 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0002_remove_region_id_alter_region_k_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('k_categoria', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('t_descripcion', models.CharField(max_length=30)),
                ('k_superior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('k_producto', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('t_nombre', models.CharField(max_length=30)),
                ('t_descripcion', models.CharField(max_length=100)),
                ('k_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='bodega',
            fields=[
                ('k_bodega', models.DecimalField(decimal_places=0, max_digits=6, primary_key=True, serialize=False)),
                ('t_direrccion', models.CharField(max_length=50)),
                ('n_telefono', models.DecimalField(decimal_places=0, max_digits=10)),
                ('k_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.region')),
            ],
        ),
        migrations.CreateModel(
            name='bode_prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_cantidad', models.DecimalField(decimal_places=0, max_digits=8)),
                ('k_bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.bodega')),
                ('k_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.producto')),
            ],
        ),
    ]
