# Generated by Django 4.0.3 on 2023-03-16 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bode_prod',
            unique_together={('k_bodega', 'k_producto')},
        ),
    ]
