create pluggable database VENTAS_MULTINIVEL admin user SUDO identified by nomelase123 roles=(connect) file_name_convert=('/opt/oracle/oradata/XE/pdbseed','/opt/oracle/oradata/CE/ventas_multinivel');
alter pluggable database VENTAS_MULTINIVEL open;

sqlplus system/nomelase..123@localhost:1521/VENTAS_MULTINIVEL;

-- ::: Crear tablespace default ::: ---
create tablespace ADMDEF datafile '/opt/oracle/oradata/XE/ADMDEF.DBF' size 512m autoextend on;
--- ::: Crear tablespace temporal ::: ---
create temporary tablespace ADMTMP tempfile '/opt/oracle/oradata/XE/ADMTMP.DBF' size 512m autoextend on;

create tablespace USERSDEF datafile '/opt/oracle/oradata/XE/USERSDEF.DBF' size 512m autoextend on;
create temporary tablespace USERSTMP tempfile '/opt/oracle/oradata/XE/USERSTMP.DBF' size 512m autoextend on;

--- ::: Creación de usuario ADMINDB ::: ---
create user ADMINDB identified by nomelase123 default tablespace ADMDEF temporary tablespace ADMTMP quota 512m on ADMDEF;
grant connect,resource to ADMINDB;
--- ::: Creación de usuario DJANGO ::: ---
CREATE TABLESPACE DJADEF DATAFILE '/opt/oracle/oradata/XE/DJADEF.DBF' SIZE 1G AUTOEXTEND ON;
CREATE TEMPORARY TABLESPACE DJATMP TEMPFILE '/opt/oracle/oradata/XE/DJATMP.DBF' SIZE 1G AUTOEXTEND ON;
CREATE USER DJANGO IDENTIFIED BY nomelase123 DEFAULT TABLESPACE DJADEF TEMPORARY TABLESPACE DJATMP QUOTA UNLIMITED ON DJADEF;
grant connect, resource TO DJANGO;

--- ::: CREAR BASE DE DATOS ::: ---

--- ::: LLENAR BASE DE DATOS ::: ---

-- Permisos para el Rol ADMINISTRADOR
create role ADMINISTRADOR;
grant CREATE USER to ADMINISTRADOR;
grant SELECT,INSERT,UPDATE on ADMINDB.BODEGA to ADMINISTRADOR;
grant SELECT,INSERT,UPDATE on ADMINDB.BODE_PROD to ADMINISTRADOR;
grant SELECT ON ADMINDB.CALISERVICIO to ADMINISTRADOR;
grant SELECT,INSERT,UPDATE on ADMINDB.CATEGORIA to ADMINISTRADOR;
grant SELECT,INSERT,UPDATE on ADMINDB.CLASIFICACION to ADMINISTRADOR;
grant SELECT,UPDATE on ADMINDB.CLIENTE to ADMINISTRADOR;
grant SELECT,INSERT,UPDATE on ADMINDB.METODOPAGO to ADMINISTRADOR;
grant SELECT on ADMINDB.PAGOPEDIDO to ADMINISTRADOR;
grant SELECT,UPDATE ON ADMINDB.PEDIDO to ADMINISTRADOR;
grant SELECT ON ADMINDB.PEDI_ITEM to ADMINISTRADOR;
grant SELECT,INSERT,UPDATE on ADMINDB.PRODUCTO to ADMINISTRADOR;
grant SELECT,INSERT,UPDATE ON ADMINDB.REGION to ADMINISTRADOR;
grant SELECT,INSERT on ADMINDB.PAIS to ADMINISTRADOR;
grant SELECT,INSERT on ADMINDB.REPRESENTANTE to ADMINISTRADOR;

-- Permisos para el Rol Cliente
create role CLIENTE;
grant UPDATE,INSERT on ADMINDB.CALISERVICIO to CLIENTE;
grant SELECT,UPDATE,INSERT on ADMINDB.PEDIDO to CLIENTE;
grant SELECT on ADMINDB.CATEGORIA to CLIENTE;
grant SELECT,UPDATE,INSERT on ADMINDB.CLIENTE to CLIENTE;
grant SELECT on ADMINDB.METODOPAGO to CLIENTE;
grant SELECT,INSERT on ADMINDB.PAGOPEDIDO to CLIENTE;
grant SELECT,UPDATE,INSERT on ADMINDB.PEDIDO to CLIENTE;
grant SELECT,UPDATE,INSERT on ADMINDB.PEDI_ITEM to CLIENTE;
grant SELECT on ADMINDB.PRODUCTO to CLIENTE;
grant SELECT on ADMINDB.REGION to CLIENTE;
grant SELECT on ADMINDB.REPRESENTANTE to CLIENTE;
grant SELECT on ADMINDB.PAIS to CLIENTE;

-- Permisos para el Rol Representante
create role REPRESENTANTE;
grant CREATE USER to REPRESENTANTE;
grant SELECT,UPDATE on ADMINDB.BODE_PROD to REPRESENTANTE;
grant SELECT on ADMINDB.CALISERVICIO to REPRESENTANTE;
grant SELECT on ADMINDB.CATEGORIA to REPRESENTANTE;
grant SELECT,INSERT on ADMINDB.CLIENTE to REPRESENTANTE;
grant SELECT,UPDATE on ADMINDB.PEDIDO to REPRESENTANTE;
grant SELECT on ADMINDB.PRODUCTO to REPRESENTANTE;
grant SELECT on ADMINDB.REGION to REPRESENTANTE;
grant SELECT,UPDATE on ADMINDB.REPRESENTANTE to REPRESENTANTE;
grant SELECT on ADMINDB.PAIS to REPRESENTANTE;

-- Permisos para el Rol Director
create role DIRECTOR;
grant CREATE USER to DIRECTOR;
grant SELECT,UPDATE,INSERT on ADMINDB.CLIENTE to DIRECTOR;
grant SELECT,UPDATE,INSERT on ADMINDB.REPRESENTANTE to DIRECTOR;


--- ROLES ::: y algunos usuarios
--- ADMINDB        -> Administrador de la base de datos
CREATE USER eladmin IDENTIFIED BY nomelase123 DEFAULT TABLESPACE USERSDEF TEMPORARY TABLESPACE USERSTMP QUOTA 2M ON USERSDEF;
GRANT ADMINISTRADOR,connect to eladmin;
--- ADMINISTRADOR  -> Administrador del aplicativo se le asigna el rol de ADMINISTRDOR (eladmin :v)
CREATE USER dircar IDENTIFIED BY nomelase123 DEFAULT TABLESPACE USERSDEF TEMPORARY TABLESPACE USERSTMP QUOTA 2M ON USERSDEF;
GRANT DIRECTOR,REPRESENTANTE,connect to dircar;
CREATE USER dirpac IDENTIFIED BY nomelase123 DEFAULT TABLESPACE USERSDEF TEMPORARY TABLESPACE USERSTMP QUOTA 2M ON USERSDEF;
GRANT DIRECTOR,REPRESENTANTE,connect to dirpac;
CREATE USER dirand IDENTIFIED BY nomelase123 DEFAULT TABLESPACE USERSDEF TEMPORARY TABLESPACE USERSTMP QUOTA 2M ON USERSDEF;
GRANT DIRECTOR,REPRESENTANTE,connect to dirand;
CREATE USER dirlao IDENTIFIED BY nomelase123 DEFAULT TABLESPACE USERSDEF TEMPORARY TABLESPACE USERSTMP QUOTA 2M ON USERSDEF;
GRANT DIRECTOR,REPRESENTANTE,connect to dirlao;
CREATE USER dirama IDENTIFIED BY nomelase123 DEFAULT TABLESPACE USERSDEF TEMPORARY TABLESPACE USERSTMP QUOTA 2M ON USERSDEF;
GRANT DIRECTOR,REPRESENTANTE,connect to dirama;
--- DIRECTOR       -> Director del aplicativo
CREATE USER repredef IDENTIFIED BY nomelase123 DEFAULT TABLESPACE USERSDEF TEMPORARY TABLESPACE USERSTMP QUOTA 2M ON USERSDEF;
GRANT REPRESENTANTE,connect to dirama;
--- REPRESENTANTE  -> Representante del aplicativo
CREATE USER client IDENTIFIED BY nomelase123 DEFAULT TABLESPACE USERSDEF TEMPORARY TABLESPACE USERSTMP QUOTA 2M ON USERSDEF;
GRANT CLIENTE,connect to dirama;
--- CLIENTE        -> Cliente del aplicativo