# Generated by Django 4.0.3 on 2023-03-14 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pais',
            fields=[
                ('k_pais', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('t_nombre', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_region', models.CharField(max_length=3)),
                ('t_nombre', models.CharField(max_length=30, unique=True)),
                ('k_pais', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='regions.pais')),
            ],
            options={
                'unique_together': {('k_region', 'k_pais')},
            },
        ),
    ]
