# Generated by Django 4.0.3 on 2023-03-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='id',
        ),
        migrations.AlterField(
            model_name='region',
            name='k_region',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
