# Generated by Django 4.0.3 on 2023-03-16 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_remove_region_id_alter_region_k_region'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='region',
            unique_together=set(),
        ),
    ]
